### ISSUE TITLE
Edit lifelines

### ISSUE THREAD

**Issue by daniel-moon32** [climateclock/h4i-uiuc-climate-clock-widget#37]
## Description
We need a way to keep track of all the lifelines and be able to remove them, edit them, and reorder them.
The list of lifelines should be potentially infinite, but only the top three are relevant.

![image](https://user-images.githubusercontent.com/36148173/160259615-ab4aed3f-4559-4792-8f7b-82698ff45896.png)

## TODO
- [ ]  Create list view of cards
- [ ] Have a way to remove and edit items
- [ ] Have a way to move items

## Useful links
- https://github.com/atlassian/react-beautiful-dnd
