### ISSUE TITLE
Edit Lifelines page Styling

### ISSUE THREAD

**Issue by daniel-moon32** [climateclock/h4i-uiuc-climate-clock-widget#70]
## Description
Finish styling for lifelines page in figma

![Screenshot from 2022-04-26 19-39-36](https://user-images.githubusercontent.com/36148173/165415488-9bc12840-0024-4c10-a380-7bb1b2cc7d6c.png)

## TODO
- [ ] Add draggable dots
- [ ] Add border color while dragging
- [ ] Add hidden list section
- [ ] Fix styling to match figma
